title:              oliver adams
email:              oliver.adams.b@gmail.com
description:        a professional archive
author:             oliver adams
baseurl:            "/"
url:                "https://oliver-adams-b.github.io"

# Social Profiles
twitter_username:   
github_username:    oliver-adams-b
facebook_username:  
instagram_username:  
linkedin_username:   www.linkedin.com/in/adams-oliver/

# Add your google-analytics ID here to activate google analytics
google_analytics:   

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
